/**
 * Re-exports Fastify types via subpath imports and augments FastifyRequest
 * with app-specific properties.
 *
 * Fastify v4 uses `export = fastify` (CJS namespace) which is incompatible with
 * named imports under `module: "esnext"` + `moduleResolution: "bundler"`.
 * Importing directly from the sub-type-files (plain `export interface`) works.
 *
 * The `declare module` blocks below augment both the subpath module (used by
 * our barrel) and the main module (used by Fastify internally) so that
 * `request.userId` is typed everywhere.
 */
export type { FastifyInstance } from 'fastify/types/instance';
export type { FastifyRequest } from 'fastify/types/request';
export type { FastifyReply } from 'fastify/types/reply';

declare module 'fastify/types/request' {
  interface FastifyRequest {
    /** Injected by requireAuth preHandler on every authenticated route. */
    userId?: string;

    /**
     * Unique ID for this HTTP request lifecycle.
     * Generated by the observability onRequest hook from X-Correlation-Id header
     * (if present) or crypto.randomUUID(). Returned to clients as X-Correlation-Id.
     * Always available after the onRequest phase — treat as non-optional in handlers.
     */
    correlationId: string;
  }
}
